# Generated by Django 5.0.6 on 2024-05-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='short_description',
        ),
        migrations.AddField(
            model_name='subsystem',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.system'),
        ),
    ]
