# Generated by Django 5.0.6 on 2024-05-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_remove_subsystem_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='facility',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
