# Generated by Django 5.0.6 on 2024-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_milestone_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
