# Generated by Django 5.0.6 on 2024-05-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0001_initial'),
        ('task_management', '0004_task_milestone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.departmentshop'),
        ),
    ]
