# Generated by Django 3.2.16 on 2024-05-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_task_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='category',
            field=models.CharField(blank=True, default='CE', max_length=8, null=True),
        ),
    ]
