# Generated by Django 3.2.16 on 2024-05-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0002_ipwhitelist_denied'),
        ('task_management', '0006_milestone_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.division'),
        ),
    ]
