# Generated by Django 3.2.16 on 2024-05-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_milestone_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutorlink',
            name='document_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='taskexecutorlink',
            name='task_acknowledged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tasksupervisorlink',
            name='document_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tasksupervisorlink',
            name='task_acknowledged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
