# Generated by Django 3.2.16 on 2024-05-23 06:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manpower', '0002_ipwhitelist_denied'),
        ('task_management', '0009_auto_20240519_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorFeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 6, 42, 27, 504907))),
            ],
            options={
                'db_table': 'distributor_feedback',
            },
        ),
        migrations.CreateModel(
            name='ExecutorFeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(blank=True, default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 6, 42, 27, 503310))),
            ],
            options={
                'db_table': 'executor_feedback',
            },
        ),
        migrations.CreateModel(
            name='QuesChoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_1', models.CharField(blank=True, default='', max_length=256)),
                ('choice_2', models.CharField(blank=True, default='', max_length=256)),
                ('choice_3', models.CharField(blank=True, default='', max_length=256)),
                ('choice_4', models.CharField(blank=True, default='', max_length=256)),
                ('correct_choice', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'db_table': 'ques_choices',
            },
        ),
        migrations.CreateModel(
            name='SupervisorFeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 6, 42, 27, 504109))),
            ],
            options={
                'db_table': 'supervisor_feedback',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_id',
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.division'),
        ),
        migrations.AddField(
            model_name='questions',
            name='employee_category',
            field=models.CharField(blank=True, default='executor', max_length=64),
        ),
        migrations.AddField(
            model_name='questions',
            name='minimum_length',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task'),
        ),
        migrations.AddField(
            model_name='questions',
            name='task_state',
            field=models.CharField(blank=True, default='pre_start', max_length=16),
        ),
        migrations.AddField(
            model_name='questionsanswers',
            name='is_approved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(blank=True, default='CEW', max_length=256),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='answer',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 6, 42, 27, 501316)),
        ),
        migrations.CreateModel(
            name='TaskFeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 6, 42, 27, 505757))),
                ('distributor_feedback', models.ManyToManyField(to='task_management.DistributorFeedBack')),
                ('executor_feedback', models.ManyToManyField(to='task_management.ExecutorFeedBack')),
                ('supervisor_feedback', models.ManyToManyField(to='task_management.SupervisorFeedBack')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task')),
            ],
            options={
                'db_table': 'task_feedback',
            },
        ),
        migrations.AddField(
            model_name='supervisorfeedback',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='task_management.QuestionsAnswers'),
        ),
        migrations.AddField(
            model_name='supervisorfeedback',
            name='executor_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.executorfeedback'),
        ),
        migrations.AddField(
            model_name='supervisorfeedback',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorfeedback',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task'),
        ),
        migrations.AddField(
            model_name='executorfeedback',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='task_management.QuestionsAnswers'),
        ),
        migrations.AddField(
            model_name='executorfeedback',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executorfeedback',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task'),
        ),
        migrations.AddField(
            model_name='distributorfeedback',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='task_management.QuestionsAnswers'),
        ),
        migrations.AddField(
            model_name='distributorfeedback',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributorfeedback',
            name='executor_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.executorfeedback'),
        ),
        migrations.AddField(
            model_name='distributorfeedback',
            name='supervisor_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.supervisorfeedback'),
        ),
        migrations.AddField(
            model_name='distributorfeedback',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task'),
        ),
        migrations.AddField(
            model_name='questions',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.queschoices'),
        ),
    ]
