# Generated by Django 3.2.16 on 2024-05-29 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_auto_20240524_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMsgInstruction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_time', models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 130956))),
                ('message_body', models.CharField(blank=True, max_length=256, null=True)),
                ('recipients', models.TextField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'group_msg_instruction',
            },
        ),
        migrations.AlterField(
            model_name='distributorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 128470)),
        ),
        migrations.AlterField(
            model_name='executorfeedback',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 126854)),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 124698)),
        ),
        migrations.AlterField(
            model_name='supervisorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 127643)),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 129341)),
        ),
    ]
