# Generated by Django 3.2.16 on 2024-05-30 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0012_auto_20240529_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 93769)),
        ),
        migrations.AlterField(
            model_name='executorfeedback',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 92155)),
        ),
        migrations.AlterField(
            model_name='groupmsginstruction',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 96224)),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 90127)),
        ),
        migrations.AlterField(
            model_name='supervisorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 92976)),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 94686)),
        ),
    ]
