# Generated by Django 3.2.16 on 2024-05-31 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0013_auto_20240530_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 59, 21, 395578), null=True),
        ),
        migrations.AlterField(
            model_name='executorfeedback',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmsginstruction',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 59, 21, 397904), null=True),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 59, 21, 394790), null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 59, 21, 396438), null=True),
        ),
        migrations.CreateModel(
            name='MsgInstructionAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 59, 21, 398154), null=True)),
                ('action_text', models.CharField(blank=True, max_length=512, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.file')),
                ('instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.groupmsginstruction')),
            ],
            options={
                'db_table': 'msg_instruction_action',
            },
        ),
    ]
