# Generated by Django 3.2.16 on 2024-05-31 21:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0014_auto_20240531_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 787115), null=True),
        ),
        migrations.AlterField(
            model_name='groupmsginstruction',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 789581), null=True),
        ),
        migrations.AlterField(
            model_name='msginstructionaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 789823), null=True),
        ),
        migrations.AlterField(
            model_name='supervisorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 786300), null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 787931), null=True),
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_documents', models.TextField(blank=True, max_length=1024, null=True)),
                ('requested_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 1, 3, 34, 26, 790264), null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('requester_remarks', models.TextField(blank=True, max_length=1024, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver_remarks', models.TextField(blank=True, max_length=1024, null=True)),
                ('provided_documents', models.TextField(blank=True, max_length=1024, null=True)),
                ('provider_remarks', models.TextField(blank=True, max_length=1024, null=True)),
                ('provided_at', models.DateTimeField(blank=True, null=True)),
                ('approval_level', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('provided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provided_by', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task')),
            ],
            options={
                'db_table': 'document_request',
            },
        ),
    ]
