# Generated by Django 3.2.16 on 2024-06-02 12:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manpower', '0002_ipwhitelist_denied'),
        ('task_management', '0015_auto_20240601_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 374230), null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='requested_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 2, 18, 42, 58, 377138), null=True),
        ),
        migrations.AlterField(
            model_name='groupmsginstruction',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 376522), null=True),
        ),
        migrations.AlterField(
            model_name='msginstructionaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 376752), null=True),
        ),
        migrations.AlterField(
            model_name='supervisorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 373413), null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 375085), null=True),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(blank=True, max_length=256, null=True)),
                ('lecture_category', models.CharField(blank=True, max_length=256, null=True)),
                ('lecture_description', models.TextField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=256, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('special_participants', models.CharField(max_length=1024)),
                ('lead_presenter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_presenter', to=settings.AUTH_USER_MODEL)),
                ('other_presenter', models.ManyToManyField(related_name='other_presenter', to=settings.AUTH_USER_MODEL)),
                ('target_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.division')),
                ('tasks', models.ManyToManyField(to='task_management.Task')),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
    ]
