# Generated by Django 3.2.16 on 2024-06-02 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0016_auto_20240602_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 23, 37, 42, 860548), null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmsginstruction',
            name='send_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='msginstructionaction',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supervisorfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 23, 37, 42, 859807), null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 23, 37, 42, 861340), null=True),
        ),
    ]
