# Generated by Django 3.2.16 on 2024-06-02 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0018_auto_20240602_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorfeedback',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supervisorfeedback',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 23, 56, 44, 125460), null=True),
        ),
    ]
