# Generated by Django 3.2.16 on 2024-06-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0020_auto_20240604_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfeedback',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
