# Generated by Django 3.2.16 on 2024-06-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0021_alter_taskfeedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lead_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_executor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='lead_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
