# Generated by Django 3.2.16 on 2024-06-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0022_auto_20240606_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='approval_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='notified_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalparticipants',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.lecture'),
        ),
        migrations.AlterModelTable(
            name='externalparticipants',
            table='external_participants',
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.TextField(blank=True, max_length=4096, null=True)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.lecture')),
            ],
            options={
                'db_table': 'lecture_attendance',
            },
        ),
    ]
