# Generated by Django 3.2.16 on 2024-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0023_auto_20240607_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='special_participants',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
