# Generated by Django 3.2.16 on 2024-06-11 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0024_alter_lecture_special_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingDistributorFeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('answers', models.ManyToManyField(blank=True, null=True, to='task_management.QuestionsAnswers')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('executor_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.executorfeedback')),
                ('supervisor_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.supervisorfeedback')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task')),
            ],
            options={
                'db_table': 'ongoing_distributor_feedback',
            },
        ),
        migrations.CreateModel(
            name='OngoingExecutorFeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(blank=True, default=0)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('answers', models.ManyToManyField(blank=True, null=True, to='task_management.QuestionsAnswers')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task')),
            ],
            options={
                'db_table': 'ongoing_executor_feedback',
            },
        ),
        migrations.CreateModel(
            name='OngoingSupervisorFeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('answers', models.ManyToManyField(blank=True, null=True, to='task_management.QuestionsAnswers')),
                ('executor_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.executorfeedback')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task')),
            ],
            options={
                'db_table': 'ongoing_supervisor_feedback',
            },
        ),
        migrations.CreateModel(
            name='OnGoingTaskFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('distributor_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.ongoingdistributorfeedback')),
                ('executor_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.ongoingexecutorfeedback')),
                ('supervisor_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.ongoingsupervisorfeedback')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task')),
            ],
            options={
                'db_table': 'ongoing_task_feedback',
            },
        ),
    ]
