# Generated by Django 3.2.16 on 2024-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0025_ongoingdistributorfeedback_ongoingexecutorfeedback_ongoingsupervisorfeedback_ongoingtaskfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='task_category',
            field=models.CharField(blank=True, default='CEW', max_length=16),
        ),
    ]
