# Generated by Django 3.2.16 on 2024-06-13 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0026_questions_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='other_participants',
            field=models.ManyToManyField(related_name='other_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
