# Generated by Django 3.2.16 on 2024-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0028_consultantlecture_consultantqa_consultanttasks_lecturefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultanttasks',
            name='report_submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
