# Generated by Django 3.2.16 on 2024-06-26 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0029_auto_20240624_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='consultant_qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.consultantqa'),
        ),
        migrations.AddField(
            model_name='comment',
            name='consultant_task_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.consultanttasks'),
        ),
        migrations.AddField(
            model_name='consultantlecture',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lecture_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultanttasks',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='activity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.activity'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.task'),
        ),
    ]
