# Generated by Django 3.2.16 on 2024-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0031_consultancyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyrequest',
            name='approval_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
