# Generated by Django 3.2.16 on 2024-12-08 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0033_task_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalDocumentReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approval_level', models.IntegerField(blank=True, null=True)),
                ('version_of_doc', models.CharField(blank=True, max_length=16, null=True)),
                ('eqipment_passport_code', models.CharField(blank=True, max_length=256, null=True)),
                ('manufacturer_of_equipment', models.CharField(blank=True, max_length=256, null=True)),
                ('safety_class', models.CharField(blank=True, max_length=256, null=True)),
                ('quality_category', models.CharField(blank=True, max_length=256, null=True)),
                ('seismic_category', models.CharField(blank=True, max_length=256, null=True)),
                ('acceptance_criteria', models.TextField(blank=True, null=True)),
                ('monitored_params', models.TextField(blank=True, null=True)),
                ('params_reflected', models.TextField(blank=True, null=True)),
                ('focusing_params', models.TextField(blank=True, null=True)),
                ('safety_measures', models.TextField(blank=True, null=True)),
                ('developed_for_rnpp', models.TextField(blank=True, null=True)),
                ('transient_situation_explanation', models.TextField(blank=True, null=True)),
                ('fulfill_design_requirements', models.TextField(blank=True, null=True)),
                ('operational_modes_reflected', models.TextField(blank=True, null=True)),
                ('align_with_scope_limit', models.TextField(blank=True, null=True)),
                ('relevant_document_bd', models.TextField(blank=True, null=True)),
                ('differences_reflected', models.TextField(blank=True, null=True)),
                ('list_of_maloperations', models.TextField(blank=True, null=True)),
                ('peripherial_important_params', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operational_document_review',
            },
        ),
    ]
