# Generated by Django 3.2.16 on 2024-12-14 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0034_operationaldocumentreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationDocumentReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approval_level', models.IntegerField(blank=True, null=True)),
                ('version_of_doc', models.CharField(blank=True, max_length=16, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('storing_entity', models.TextField(blank=True, null=True)),
                ('is_applicable', models.TextField(blank=True, null=True)),
                ('specific_users_of_document', models.TextField(blank=True, null=True)),
                ('other_users_of_document', models.TextField(blank=True, null=True)),
                ('user_qualification', models.TextField(blank=True, null=True)),
                ('safety_measures', models.TextField(blank=True, null=True)),
                ('record_of_work', models.TextField(blank=True, null=True)),
                ('deviation_notification_reporting', models.TextField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('next_review_dept_person', models.TextField(blank=True, null=True)),
                ('test_procedures_valid_logical', models.TextField(blank=True, null=True)),
                ('limits_of_normal_operations', models.TextField(blank=True, null=True)),
                ('reason_to_keep_gost_docs', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulation_document_review',
            },
        ),
        migrations.CreateModel(
            name='FireAndEmergencyDocumentReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approval_level', models.IntegerField(blank=True, null=True)),
                ('version_of_doc', models.CharField(blank=True, max_length=16, null=True)),
                ('equipment_passport_code', models.CharField(blank=True, max_length=256, null=True)),
                ('safety_class', models.CharField(blank=True, max_length=256, null=True)),
                ('quality_category', models.CharField(blank=True, max_length=256, null=True)),
                ('seismic_category', models.CharField(blank=True, max_length=256, null=True)),
                ('hydrant_piping_acceptance_criteria', models.TextField(blank=True, null=True)),
                ('success_criteria_params', models.TextField(blank=True, null=True)),
                ('bangladesh_compliance', models.TextField(blank=True, null=True)),
                ('bd_standard_practice', models.TextField(blank=True, null=True)),
                ('compliance_waste_water_accum', models.TextField(blank=True, null=True)),
                ('fire_drill_frequency', models.TextField(blank=True, null=True)),
                ('steps_need_to_take', models.TextField(blank=True, null=True)),
                ('safety_gear_standards', models.TextField(blank=True, null=True)),
                ('water_level_bd_compliance', models.TextField(blank=True, null=True)),
                ('foam_flooding_scope', models.TextField(blank=True, null=True)),
                ('role_of_personnel', models.TextField(blank=True, null=True)),
                ('align_with_rnpp', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fire_emergency_document_review',
            },
        ),
    ]
