# Generated by Django 3.2.16 on 2024-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0035_fireandemergencydocumentreview_regulationdocumentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
