# Generated by Django 3.2.16 on 2024-12-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0036_auto_20241217_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='OthersDocumentReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approval_level', models.IntegerField(blank=True, null=True)),
                ('document_category', models.CharField(blank=True, max_length=256, null=True)),
                ('version_of_doc', models.CharField(blank=True, max_length=16, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('storing_entity', models.TextField(blank=True, null=True)),
                ('for_bd', models.TextField(blank=True, null=True)),
                ('users_of_document', models.TextField(blank=True, null=True)),
                ('general_feedback', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
