# Generated by Django 3.2.16 on 2024-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0037_othersdocumentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireandemergencydocumentreview',
            name='general_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationaldocumentreview',
            name='general_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulationdocumentreview',
            name='general_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
