# Generated by Django 3.2.16 on 2025-01-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0038_auto_20241222_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='task_id',
        ),
    ]
