# Generated by Django 3.2.16 on 2025-01-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0004_approvalsignature_committee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0039_auto_20250105_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondTierDocumentReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('committee_deadline', models.DateField(blank=True, null=True)),
                ('chief_eng_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chief_eng_approval', to='manpower.approvalsignature')),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.committee')),
                ('committee_approval', models.ManyToManyField(blank=True, null=True, related_name='second_tier_committee_approval', to='manpower.ApprovalSignature')),
                ('division_head_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_head_approval', to='manpower.approvalsignature')),
                ('fire_doc_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.fireandemergencydocumentreview')),
                ('op_doc_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.operationaldocumentreview')),
                ('other_doc_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.othersdocumentreview')),
                ('regulation_doc_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.regulationdocumentreview')),
                ('sd_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sd_approval', to='manpower.approvalsignature')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.task')),
            ],
            options={
                'db_table': 'second_tier_document_review',
            },
        ),
        migrations.CreateModel(
            name='SecondTierCommitteeFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateField(blank=True, null=True)),
                ('approval_or_revise', models.CharField(blank=True, max_length=256, null=True)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.committee')),
                ('feedback_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'second_tier_committee_feedback',
            },
        ),
        migrations.CreateModel(
            name='DocumentReviewComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('section_no', models.CharField(blank=True, max_length=256, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('proposed_text', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reply_on', models.DateTimeField(blank=True, null=True)),
                ('proposal_acceptance', models.TextField(blank=True, null=True)),
                ('reply_remarks', models.TextField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_comment_proposed_by', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_comment_replied_by', to=settings.AUTH_USER_MODEL)),
                ('second_tier_committee_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.secondtiercommitteefeedback')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task')),
            ],
            options={
                'db_table': 'document_review_comments',
            },
        ),
    ]
