# Generated by Django 3.2.16 on 2025-01-27 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0005_safetyanalysisreportcommittee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0041_auto_20250112_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAnalysisReportReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_section', models.CharField(blank=True, max_length=1024, null=True)),
                ('assigned_section_title', models.CharField(blank=True, max_length=2048, null=True)),
                ('analysis_report_file', models.CharField(blank=True, max_length=256, null=True)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('submitted_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.safetyanalysisreportcommittee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sar_submitted_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sar_chapter_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_analysis_report_review',
            },
        ),
    ]
