# Generated by Django 3.2.16 on 2025-02-08 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manpower', '0005_safetyanalysisreportcommittee'),
        ('task_management', '0042_safetyanalysisreportreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SARCommitteeReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_report_file', models.CharField(blank=True, max_length=256, null=True)),
                ('submitted_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manpower.safetyanalysisreportcommittee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sar_cmt_report_submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sar_committee_report',
            },
        ),
    ]
