# Generated by Django 5.0.6 on 2024-05-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentShop',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=256, null=True)),
                ('dept_code', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'department_shop',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('div_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=256, null=True)),
                ('subnet', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=16, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'ip_whitelist',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=256)),
                ('section_details', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('subdepartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdepartment_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('npcbl_designation', models.CharField(blank=True, max_length=256, null=True)),
                ('designation', models.CharField(blank=True, max_length=256, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=16, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_executor', models.BooleanField(default=True)),
                ('access_level', models.IntegerField(default=0)),
                ('email_validation_token', models.CharField(blank=True, max_length=128, null=True)),
                ('validation_expire_date_time', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.departmentshop')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.section')),
                ('subdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.subdepartment')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
