# Generated by Django 3.2.16 on 2024-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipwhitelist',
            name='denied',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
