# Generated by Django 3.2.16 on 2025-01-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0002_ipwhitelist_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
