# Generated by Django 3.2.16 on 2025-01-27 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manpower', '0004_approvalsignature_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAnalysisReportCommittee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('sar_section', models.CharField(blank=True, max_length=512, null=True)),
                ('sar_section_title', models.CharField(blank=True, max_length=512, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='sar_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
