# Generated by Django 3.2.16 on 2025-03-03 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manpower', '0005_safetyanalysisreportcommittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalsignature',
            name='remarks_1',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='UserConsentDocReviewRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consent_msg', models.CharField(blank=True, max_length=512, null=True)),
                ('consent_given_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_consent_doc_review_remarks',
            },
        ),
    ]
