# Generated by Django 5.0.4 on 2025-06-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0006_auto_20250303_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalsignature',
            name='remarks_1',
        ),
    ]
