# Generated by Django 5.0.4 on 2025-06-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0007_remove_approvalsignature_remarks_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalsignature',
            name='remarks_1',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
