# Generated by Django 5.0.4 on 2025-03-10 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manpower', '0006_auto_20250303_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_no', models.CharField(blank=True, max_length=11, null=True)),
                ('ts_doc_code', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('ase_ref_letter', models.CharField(blank=True, max_length=512, null=True)),
                ('ase_ref_letter_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('facility_kks', models.CharField(blank=True, max_length=512, null=True)),
                ('relevant_wd_code', models.CharField(blank=True, max_length=512, null=True)),
                ('reason_for_ts', models.TextField(blank=True, null=True)),
                ('modification_type', models.CharField(blank=True, max_length=512, null=True)),
                ('deadline_for_temporary_solution', models.DateField(blank=True, null=True)),
                ('ts_file', models.CharField(blank=True, max_length=512, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manpower.division')),
                ('shop', models.ManyToManyField(to='manpower.departmentshop')),
            ],
            options={
                'db_table': 'technical_solution',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSolutionReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('responsible_personnel', models.ManyToManyField(related_name='ts_responsible_personnel', to=settings.AUTH_USER_MODEL)),
                ('review_personnel', models.ManyToManyField(related_name='ts_assigned_personnel', to=settings.AUTH_USER_MODEL)),
                ('technical_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_solution.technicalsolution')),
            ],
            options={
                'db_table': 'ts_review',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSolutionRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_signature', models.ManyToManyField(to='manpower.approvalsignature')),
                ('technical_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_solution.technicalsolution')),
                ('ts_review_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_solution.technicalsolutionreview')),
            ],
            options={
                'db_table': 'ts_recommendation',
            },
        ),
    ]
