# Generated by Django 5.0.4 on 2025-06-24 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_solution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsolution',
            name='deadline_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalsolutionrecommendation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='technicalsolutionreview',
            name='oesd_personnel',
            field=models.ManyToManyField(related_name='oesd_personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technicalsolution',
            name='relevant_wd_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technicalsolutionreview',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TSOESDRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('remarks_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_oesd_remarks_from', to=settings.AUTH_USER_MODEL)),
                ('technical_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_solution.technicalsolution')),
            ],
            options={
                'db_table': 'ts_oesd_remarks',
            },
        ),
        migrations.CreateModel(
            name='TSShopRemarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('remarks_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_shop_remarks_from', to=settings.AUTH_USER_MODEL)),
                ('technical_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_solution.technicalsolution')),
            ],
            options={
                'db_table': 'ts_shop_remarks',
            },
        ),
    ]
