"""
Django settings for project_management_system project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from operational_management_system import db_settings
from operational_management_system import ftp_settings
from operational_management_system import tokens
from pathlib import Path
import pytz
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oi#gpytb7_04j3mbrpd@rj(0d&4l-it(6upc4*xl9ue+#gej2n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'task_management.apps.TaskManagementConfig',
    "manpower.apps.ManpowerConfig",
    "system_log.apps.SystemLogConfig",
    "technical_solution.apps.TechnicalSolutionConfig",
]

MIDDLEWARE = [
    'task_management.middleware.IPFilterMiddleWare',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'operational_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'operational_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = db_settings.db_settings_parameters
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'
PYTZ_TIME_ZONE =  pytz.timezone("Asia/Dhaka")
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static/")
    ]
    STATIC_URL = "/static/"

if not DEBUG:
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
    print(STATIC_ROOT)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FTP_SERVER = ftp_settings.SERVER
FTP_USER = ftp_settings.USER
FTP_PWD = ftp_settings.PWD
FTP_BASE_DIR = ftp_settings.FTP_BASEDIR

# TO show rendered document in iframe, we need to enable this
X_FRAME_OPTIONS = 'SAMEORIGIN'

SMS_TOKEN = tokens.sms_token
EMAIL_SENDER = tokens.email_sender
EMAIL_PASS = tokens.email_sender_pass
EMAIL_HOST = tokens.email_server
SMTP_PORT = 587

# Since ROMS & PMS are running under same ip (123.49.52.82) so, browser will set single sessionID, single cokkie_name and single crsf token,
# while logging into PMS, ROMS will automatically logout and vice versa. So we need to explicitly set SESSION_COOKIE_NAME AND CSRF_TOKEN for both apps,
# to avoid this issue.

SESSION_COOKIE_NAME = 'roms_sessionid'
CSRF_COOKIE_NAME = 'roms_csrftoken'

