# Generated by Django 5.0.6 on 2024-05-10 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAndSMSLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('phone_no', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('message_body', models.CharField(blank=True, max_length=512, null=True)),
                ('sms_success', models.BooleanField(default=False)),
                ('sms_error_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('email_error_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('email_success', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_sms_log',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('message_body', models.CharField(blank=True, max_length=512, null=True)),
                ('viewed_at', models.DateTimeField(null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_log',
            },
        ),
    ]
