# Generated by Django 3.2.16 on 2024-05-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0002_mailandsmslog_usernotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('task_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'task_log',
            },
        ),
    ]
