# Generated by Django 3.2.16 on 2024-05-29 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0012_auto_20240529_1207'),
        ('system_log', '0003_tasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailandsmslog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 134518), null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='added_executor',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='added_supervisor',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 133066)),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='removed_executor',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='removed_supervisor',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task_management.task'),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 133425), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 133770), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 132788), null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 7, 34, 132532), null=True),
        ),
    ]
