# Generated by Django 3.2.16 on 2024-05-30 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0004_auto_20240529_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='approval_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 98769), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 99119), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 98115), null=True),
        ),
        migrations.AlterField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 99804), null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 98395)),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 14, 12, 10, 97838), null=True),
        ),
    ]
