# Generated by Django 3.2.16 on 2024-05-31 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0006_auto_20240531_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 791924), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 792166), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 791217), null=True),
        ),
        migrations.AlterField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 792829), null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 791575), null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 3, 34, 26, 790953), null=True),
        ),
    ]
