# Generated by Django 3.2.16 on 2024-06-02 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0007_auto_20240601_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 379939), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 380274), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 379327), null=True),
        ),
        migrations.AlterField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 380955), null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 379590), null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 42, 58, 379083), null=True),
        ),
    ]
