# Generated by Django 3.2.16 on 2024-06-05 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0013_auto_20240604_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('ip', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'password_change_log',
            },
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 15, 38, 888654), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 15, 38, 888897), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 15, 38, 887967), null=True),
        ),
        migrations.AlterField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 15, 38, 889565), null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 15, 38, 887718), null=True),
        ),
    ]
