# Generated by Django 3.2.16 on 2024-06-06 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0014_auto_20240605_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 16, 2, 44, 680933), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 16, 2, 44, 681193), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 16, 2, 44, 680184), null=True),
        ),
        migrations.AlterField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 16, 2, 44, 681942), null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 16, 2, 44, 679932), null=True),
        ),
    ]
