# Generated by Django 3.2.16 on 2024-06-13 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0019_auto_20240611_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 29, 57, 840662), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 29, 57, 840911), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 29, 57, 840059), null=True),
        ),
        migrations.AlterField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 29, 57, 841594), null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 29, 57, 839820), null=True),
        ),
    ]
