# Generated by Django 3.2.16 on 2025-02-02 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0040_auto_20250127_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_header', models.TextField(blank=True, null=True)),
                ('url_target', models.CharField(blank=True, max_length=256, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
                ('expire_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'notice_board',
            },
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 17, 53, 4, 512304), null=True),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 17, 53, 4, 512546), null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 17, 53, 4, 511701), null=True),
        ),
        migrations.AlterField(
            model_name='mailandsmslog',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 17, 53, 4, 513199), null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 17, 53, 4, 511438), null=True),
        ),
    ]
